### ISSUE TITLE
language agnostic master issue

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/architect#183]
We've made the first steps into making Architect a language agnostic framework by removing the need for function dependencies and enabling per function opt-in to runtimes other than Node. 

This issue will track our progress to enabling first class support for Python, Go, .NET and Java.

---

- [x] opt into non default (node8.10) runtimes with `.arc-config` https://github.com/arc-repos/architect/pull/179/commits/9b532c38e5cd6a5c27da14406cca8bdc135fabc0
- [x] remove node references from banner
- [x] setup sandbox to use a child process (instead of dynamically loading lambdas as node modules)
- [x] ensure all workflows use the module behind `npx inventory` (which removes reliance on package.json)
- [x] figure out how `/views` and `/shared` work for functions that do not have `node_modules`
- [x] change default `npx create` runtime using `.arc` with `@aws` pragma
- [ ]  begin distributing an arc binary for all platforms (removing top level node dep… but we will continue to support npx workflows and node-first dev) using https://github.com/zeit/pkg

# python
- [x] npx sandbox support
- [x] http function hello world in python
- [x] event function hello world in python
- [x] queue function hello world in python
- [x] scheduled function hello world in python
- [x] table function(s) hello world in python

# ruby
- [x] npx sandbox support
- [x] http function hello world in python
- [x] event function hello world in python
- [x] queue function hello world in python
- [x] scheduled function hello world in python
- [x] table function(s) hello world in python

**Comment by ryanblock** [comment]
Some of this is stale, but a lot is in and has been for a while. Will close for now and reopen as individual, language-specific issues as they arrive and receive first class support.
